using System;
using System.ComponentModel;
using System.Configuration;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Web.Security.Cryptography;
using System.Web.Util;

namespace System.Web.Configuration
{
	/// <summary>Defines the configuration settings that control the key generation and algorithms that are used in encryption, decryption, and message authentication code (MAC) operations in Windows Forms authentication, view-state validation, and session-state application isolation. This class cannot be inherited.</summary>
	// Token: 0x02000713 RID: 1811
	public sealed class MachineKeySection : ConfigurationSection
	{
		// Token: 0x17001921 RID: 6433
		// (get) Token: 0x0600571C RID: 22300 RVA: 0x0013008E File Offset: 0x0012E28E
		internal static bool IsDecryptionKeyAutogenerated
		{
			get
			{
				MachineKeySection.EnsureConfig();
				return MachineKeySection.s_config.AutogenKey;
			}
		}

		// Token: 0x17001922 RID: 6434
		// (get) Token: 0x0600571D RID: 22301 RVA: 0x0013009F File Offset: 0x0012E29F
		internal bool AutogenKey
		{
			get
			{
				this.RuntimeDataInitialize();
				return this._AutogenKey;
			}
		}

		// Token: 0x17001923 RID: 6435
		// (get) Token: 0x0600571E RID: 22302 RVA: 0x001300AD File Offset: 0x0012E2AD
		internal byte[] ValidationKeyInternal
		{
			get
			{
				this.RuntimeDataInitialize();
				return (byte[])this._ValidationKey.Clone();
			}
		}

		// Token: 0x17001924 RID: 6436
		// (get) Token: 0x0600571F RID: 22303 RVA: 0x001300C5 File Offset: 0x0012E2C5
		internal byte[] DecryptionKeyInternal
		{
			get
			{
				this.RuntimeDataInitialize();
				return (byte[])this._DecryptionKey.Clone();
			}
		}

		// Token: 0x17001925 RID: 6437
		// (get) Token: 0x06005720 RID: 22304 RVA: 0x001300DD File Offset: 0x0012E2DD
		internal static int HashSize
		{
			get
			{
				MachineKeySection.EnsureConfig();
				MachineKeySection.s_config.RuntimeDataInitialize();
				return MachineKeySection._HashSize;
			}
		}

		// Token: 0x17001926 RID: 6438
		// (get) Token: 0x06005721 RID: 22305 RVA: 0x001300F3 File Offset: 0x0012E2F3
		internal static int ValidationKeySize
		{
			get
			{
				MachineKeySection.EnsureConfig();
				MachineKeySection.s_config.RuntimeDataInitialize();
				return MachineKeySection._AutoGenValidationKeySize;
			}
		}

		// Token: 0x06005722 RID: 22306 RVA: 0x0013010C File Offset: 0x0012E30C
		static MachineKeySection()
		{
			MachineKeySection._properties.Add(MachineKeySection._propValidationKey);
			MachineKeySection._properties.Add(MachineKeySection._propDecryptionKey);
			MachineKeySection._properties.Add(MachineKeySection._propValidation);
			MachineKeySection._properties.Add(MachineKeySection._propDecryption);
			MachineKeySection._properties.Add(MachineKeySection._propCompatibilityMode);
			MachineKeySection._properties.Add(MachineKeySection._propDataProtectorType);
			MachineKeySection._properties.Add(MachineKeySection._propApplicationName);
		}

		// Token: 0x17001927 RID: 6439
		// (get) Token: 0x06005724 RID: 22308 RVA: 0x001302F6 File Offset: 0x0012E4F6
		internal static MachineKeyCompatibilityMode CompatMode
		{
			get
			{
				return MachineKeySection.GetApplicationConfig().CompatibilityMode;
			}
		}

		// Token: 0x17001928 RID: 6440
		// (get) Token: 0x06005725 RID: 22309 RVA: 0x00130302 File Offset: 0x0012E502
		protected override ConfigurationPropertyCollection Properties
		{
			get
			{
				return MachineKeySection._properties;
			}
		}

		/// <summary>Gets or sets the key that is used to validate forms authentication and view state data, or the process by which the key is generated. </summary>
		/// <returns>A key value, or a value that indicates how the key is generated. The default is "AutoGenerate,IsolateApps".</returns>
		// Token: 0x17001929 RID: 6441
		// (get) Token: 0x06005726 RID: 22310 RVA: 0x00130309 File Offset: 0x0012E509
		// (set) Token: 0x06005727 RID: 22311 RVA: 0x0013031B File Offset: 0x0012E51B
		[ConfigurationProperty("validationKey", DefaultValue = "AutoGenerate,IsolateApps")]
		[TypeConverter(typeof(WhiteSpaceTrimStringConverter))]
		[StringValidator(MinLength = 1)]
		public string ValidationKey
		{
			get
			{
				return (string)base[MachineKeySection._propValidationKey];
			}
			set
			{
				base[MachineKeySection._propValidationKey] = value;
			}
		}

		/// <summary>Gets or sets the key that is used to encrypt and decrypt data, or the process by which the key is generated. </summary>
		/// <returns>A key value, or a value that indicates how the key is generated. The default is "AutoGenerate,IsolateApps".</returns>
		// Token: 0x1700192A RID: 6442
		// (get) Token: 0x06005728 RID: 22312 RVA: 0x00130329 File Offset: 0x0012E529
		// (set) Token: 0x06005729 RID: 22313 RVA: 0x0013033B File Offset: 0x0012E53B
		[ConfigurationProperty("decryptionKey", DefaultValue = "AutoGenerate,IsolateApps")]
		[TypeConverter(typeof(WhiteSpaceTrimStringConverter))]
		[StringValidator(MinLength = 1)]
		public string DecryptionKey
		{
			get
			{
				return (string)base[MachineKeySection._propDecryptionKey];
			}
			set
			{
				base[MachineKeySection._propDecryptionKey] = value;
			}
		}

		/// <summary>Specifies the encryption algorithm that is used for encrypting and decrypting forms authentication data. </summary>
		/// <returns>A value that indicates the algorithm that is used to encrypt and decrypt forms authentication data. (For information about how to specify the algorithm that is used when view state is encrypted, see the <see cref="P:System.Web.Configuration.MachineKeySection.Validation" /> property.) <see langword="Auto" /> is the default value.</returns>
		/// <exception cref="T:System.Configuration.ConfigurationErrorsException">The selected value is not one of the decryption values.</exception>
		// Token: 0x1700192B RID: 6443
		// (get) Token: 0x0600572A RID: 22314 RVA: 0x0013034C File Offset: 0x0012E54C
		// (set) Token: 0x0600572B RID: 22315 RVA: 0x001303E8 File Offset: 0x0012E5E8
		[ConfigurationProperty("decryption", DefaultValue = "Auto")]
		[TypeConverter(typeof(WhiteSpaceTrimStringConverter))]
		[StringValidator(MinLength = 1)]
		public string Decryption
		{
			get
			{
				string decryptionAttributeSkipValidation = this.GetDecryptionAttributeSkipValidation();
				if (decryptionAttributeSkipValidation != "Auto" && decryptionAttributeSkipValidation != "AES" && decryptionAttributeSkipValidation != "3DES" && decryptionAttributeSkipValidation != "DES" && !decryptionAttributeSkipValidation.StartsWith("alg:", StringComparison.Ordinal))
				{
					throw new ConfigurationErrorsException(SR.GetString("Wrong_decryption_enum"), base.ElementInformation.Properties["decryption"].Source, base.ElementInformation.Properties["decryption"].LineNumber);
				}
				return decryptionAttributeSkipValidation;
			}
			set
			{
				if (value != "AES" && value != "3DES" && value != "Auto" && value != "DES" && !value.StartsWith("alg:", StringComparison.Ordinal))
				{
					throw new ConfigurationErrorsException(SR.GetString("Wrong_decryption_enum"), base.ElementInformation.Properties["decryption"].Source, base.ElementInformation.Properties["decryption"].LineNumber);
				}
				base[MachineKeySection._propDecryption] = value;
			}
		}

		// Token: 0x0600572C RID: 22316 RVA: 0x00130487 File Offset: 0x0012E687
		internal string GetDecryptionAttributeSkipValidation()
		{
			return ((string)base[MachineKeySection._propDecryption]) ?? "Auto";
		}

		/// <summary>Gets or sets the name of a custom algorithm that is used to validate forms authentication and view state data.</summary>
		/// <returns>A string that contains the name of a predefined algorithm or the name of a custom algorithm. </returns>
		// Token: 0x1700192C RID: 6444
		// (get) Token: 0x0600572D RID: 22317 RVA: 0x001304A2 File Offset: 0x0012E6A2
		// (set) Token: 0x0600572E RID: 22318 RVA: 0x001304B8 File Offset: 0x0012E6B8
		[ConfigurationProperty("validation", DefaultValue = "HMACSHA256")]
		[TypeConverter(typeof(WhiteSpaceTrimStringConverter))]
		[StringValidator(MinLength = 1)]
		public string ValidationAlgorithm
		{
			get
			{
				if (!this._validationIsCached)
				{
					this.CacheValidation();
				}
				return this._cachedValidation;
			}
			set
			{
				if (this._validationIsCached && value == this._cachedValidation)
				{
					return;
				}
				if (value == null)
				{
					value = "HMACSHA256";
				}
				this._cachedValidationEnum = MachineKeyValidationConverter.ConvertToEnum(value);
				this._cachedValidation = value;
				base[MachineKeySection._propValidation] = value;
				this._validationIsCached = true;
			}
		}

		// Token: 0x0600572F RID: 22319 RVA: 0x0013050C File Offset: 0x0012E70C
		internal string GetValidationAttributeSkipValidation()
		{
			return ((string)base[MachineKeySection._propValidation]) ?? "HMACSHA256";
		}

		// Token: 0x06005730 RID: 22320 RVA: 0x00130527 File Offset: 0x0012E727
		private void CacheValidation()
		{
			this._cachedValidation = this.GetValidationAttributeSkipValidation();
			this._cachedValidationEnum = MachineKeyValidationConverter.ConvertToEnum(this._cachedValidation);
			this._validationIsCached = true;
		}

		/// <summary>Specifies the hashing algorithm that is used for validating forms authentication and view state data. </summary>
		/// <returns>A value that indicates the hashing algorithm that is used to validate forms authentication and view state data.</returns>
		// Token: 0x1700192D RID: 6445
		// (get) Token: 0x06005731 RID: 22321 RVA: 0x0013054D File Offset: 0x0012E74D
		// (set) Token: 0x06005732 RID: 22322 RVA: 0x00130563 File Offset: 0x0012E763
		public MachineKeyValidation Validation
		{
			get
			{
				if (!this._validationIsCached)
				{
					this.CacheValidation();
				}
				return this._cachedValidationEnum;
			}
			set
			{
				if (this._validationIsCached && value == this._cachedValidationEnum)
				{
					return;
				}
				this._cachedValidation = MachineKeyValidationConverter.ConvertFromEnum(value);
				this._cachedValidationEnum = value;
				base[MachineKeySection._propValidation] = this._cachedValidation;
				this._validationIsCached = true;
			}
		}

		/// <summary>Gets or sets the name of the data protector type. The default is <see cref="F:System.String.Empty" />.</summary>
		/// <returns>The name of the data protector type.</returns>
		// Token: 0x1700192E RID: 6446
		// (get) Token: 0x06005733 RID: 22323 RVA: 0x001305A2 File Offset: 0x0012E7A2
		// (set) Token: 0x06005734 RID: 22324 RVA: 0x001305B4 File Offset: 0x0012E7B4
		[ConfigurationProperty("dataProtectorType", DefaultValue = "")]
		[TypeConverter(typeof(WhiteSpaceTrimStringConverter))]
		public string DataProtectorType
		{
			get
			{
				return (string)base[MachineKeySection._propDataProtectorType];
			}
			set
			{
				base[MachineKeySection._propDataProtectorType] = value;
			}
		}

		/// <summary>Gets or sets the name of the application.</summary>
		/// <returns>The name of the application. The default is <see cref="F:System.String.Empty" />.</returns>
		// Token: 0x1700192F RID: 6447
		// (get) Token: 0x06005735 RID: 22325 RVA: 0x001305C2 File Offset: 0x0012E7C2
		// (set) Token: 0x06005736 RID: 22326 RVA: 0x001305D4 File Offset: 0x0012E7D4
		[ConfigurationProperty("applicationName", DefaultValue = "")]
		[TypeConverter(typeof(WhiteSpaceTrimStringConverter))]
		public string ApplicationName
		{
			get
			{
				return (string)base[MachineKeySection._propApplicationName];
			}
			set
			{
				base[MachineKeySection._propApplicationName] = value;
			}
		}

		/// <summary>Gets or sets a value that specifies whether upgraded encryption methods for view state that were introduced after the .NET Framework version 2.0 Service Pack 1 release are used.</summary>
		/// <returns>A value that indicates whether encryption methods that were introduced after the .NET Framework 2.0 SP1 release are used. </returns>
		// Token: 0x17001930 RID: 6448
		// (get) Token: 0x06005737 RID: 22327 RVA: 0x001305E2 File Offset: 0x0012E7E2
		// (set) Token: 0x06005738 RID: 22328 RVA: 0x00130609 File Offset: 0x0012E809
		[ConfigurationProperty("compatibilityMode", DefaultValue = MachineKeyCompatibilityMode.Framework20SP1)]
		public MachineKeyCompatibilityMode CompatibilityMode
		{
			get
			{
				if (this._compatibilityMode < MachineKeyCompatibilityMode.Framework20SP1)
				{
					this._compatibilityMode = (MachineKeyCompatibilityMode)base[MachineKeySection._propCompatibilityMode];
				}
				return this._compatibilityMode;
			}
			set
			{
				base[MachineKeySection._propCompatibilityMode] = value;
				this._compatibilityMode = value;
			}
		}

		// Token: 0x06005739 RID: 22329 RVA: 0x00130624 File Offset: 0x0012E824
		protected override void Reset(ConfigurationElement parentElement)
		{
			MachineKeySection machineKeySection = parentElement as MachineKeySection;
			base.Reset(parentElement);
		}

		// Token: 0x0600573A RID: 22330 RVA: 0x00130644 File Offset: 0x0012E844
		private void RuntimeDataInitialize()
		{
			if (!this.DataInitialized)
			{
				byte[] array = null;
				bool flag = false;
				string text = this.ValidationKey;
				string text2 = HttpRuntime.AppDomainAppVirtualPath;
				string appDomainAppId = HttpRuntime.AppDomainAppId;
				this.InitValidationAndEncyptionSizes();
				if (text2 == null)
				{
					text2 = Process.GetCurrentProcess().MainModule.ModuleName;
					if (this.ValidationKey.Contains("AutoGenerate") || this.DecryptionKey.Contains("AutoGenerate"))
					{
						flag = true;
						array = new byte[MachineKeySection._AutoGenValidationKeySize + MachineKeySection._AutoGenDecryptionKeySize];
						MachineKeySection.RandomNumberGenerator.GetBytes(array);
					}
				}
				bool flag2 = StringUtil.StringEndsWith(text, ",IsolateByAppId");
				if (flag2)
				{
					text = text.Substring(0, text.Length - ",IsolateByAppId".Length);
				}
				bool flag3 = StringUtil.StringEndsWith(text, ",IsolateApps");
				if (flag3)
				{
					text = text.Substring(0, text.Length - ",IsolateApps".Length);
				}
				if (text == "AutoGenerate")
				{
					this._ValidationKey = new byte[MachineKeySection._AutoGenValidationKeySize];
					if (flag)
					{
						Buffer.BlockCopy(array, 0, this._ValidationKey, 0, MachineKeySection._AutoGenValidationKeySize);
					}
					else
					{
						Buffer.BlockCopy(HttpRuntime.s_autogenKeys, 0, this._ValidationKey, 0, MachineKeySection._AutoGenValidationKeySize);
					}
				}
				else
				{
					if (text.Length < 40 || (text.Length & 1) == 1)
					{
						throw new ConfigurationErrorsException(SR.GetString("Unable_to_get_cookie_authentication_validation_key", new object[] { text.Length.ToString(CultureInfo.InvariantCulture) }), base.ElementInformation.Properties["validationKey"].Source, base.ElementInformation.Properties["validationKey"].LineNumber);
					}
					this._ValidationKey = MachineKeySection.HexStringToByteArray(text);
					if (this._ValidationKey == null)
					{
						throw new ConfigurationErrorsException(SR.GetString("Invalid_validation_key"), base.ElementInformation.Properties["validationKey"].Source, base.ElementInformation.Properties["validationKey"].LineNumber);
					}
				}
				if (flag3)
				{
					int nonRandomizedStringComparerHashCode = StringUtil.GetNonRandomizedStringComparerHashCode(text2);
					this._ValidationKey[0] = (byte)(nonRandomizedStringComparerHashCode & 255);
					this._ValidationKey[1] = (byte)((nonRandomizedStringComparerHashCode & 65280) >> 8);
					this._ValidationKey[2] = (byte)((nonRandomizedStringComparerHashCode & 16711680) >> 16);
					this._ValidationKey[3] = (byte)(((long)nonRandomizedStringComparerHashCode & (long)((ulong)(-16777216))) >> 24);
				}
				if (flag2)
				{
					int nonRandomizedStringComparerHashCode2 = StringUtil.GetNonRandomizedStringComparerHashCode(appDomainAppId);
					this._ValidationKey[4] = (byte)(nonRandomizedStringComparerHashCode2 & 255);
					this._ValidationKey[5] = (byte)((nonRandomizedStringComparerHashCode2 & 65280) >> 8);
					this._ValidationKey[6] = (byte)((nonRandomizedStringComparerHashCode2 & 16711680) >> 16);
					this._ValidationKey[7] = (byte)(((long)nonRandomizedStringComparerHashCode2 & (long)((ulong)(-16777216))) >> 24);
				}
				text = this.DecryptionKey;
				flag2 = StringUtil.StringEndsWith(text, ",IsolateByAppId");
				if (flag2)
				{
					text = text.Substring(0, text.Length - ",IsolateByAppId".Length);
				}
				flag3 = StringUtil.StringEndsWith(text, ",IsolateApps");
				if (flag3)
				{
					text = text.Substring(0, text.Length - ",IsolateApps".Length);
				}
				if (text == "AutoGenerate")
				{
					this._DecryptionKey = new byte[MachineKeySection._AutoGenDecryptionKeySize];
					if (flag)
					{
						Buffer.BlockCopy(array, MachineKeySection._AutoGenValidationKeySize, this._DecryptionKey, 0, MachineKeySection._AutoGenDecryptionKeySize);
					}
					else
					{
						Buffer.BlockCopy(HttpRuntime.s_autogenKeys, MachineKeySection._AutoGenValidationKeySize, this._DecryptionKey, 0, MachineKeySection._AutoGenDecryptionKeySize);
					}
					this._AutogenKey = true;
				}
				else
				{
					this._AutogenKey = false;
					if ((text.Length & 1) != 0)
					{
						throw new ConfigurationErrorsException(SR.GetString("Invalid_decryption_key"), base.ElementInformation.Properties["decryptionKey"].Source, base.ElementInformation.Properties["decryptionKey"].LineNumber);
					}
					this._DecryptionKey = MachineKeySection.HexStringToByteArray(text);
					if (this._DecryptionKey == null)
					{
						throw new ConfigurationErrorsException(SR.GetString("Invalid_decryption_key"), base.ElementInformation.Properties["decryptionKey"].Source, base.ElementInformation.Properties["decryptionKey"].LineNumber);
					}
				}
				if (flag3)
				{
					int nonRandomizedStringComparerHashCode3 = StringUtil.GetNonRandomizedStringComparerHashCode(text2);
					this._DecryptionKey[0] = (byte)(nonRandomizedStringComparerHashCode3 & 255);
					this._DecryptionKey[1] = (byte)((nonRandomizedStringComparerHashCode3 & 65280) >> 8);
					this._DecryptionKey[2] = (byte)((nonRandomizedStringComparerHashCode3 & 16711680) >> 16);
					this._DecryptionKey[3] = (byte)(((long)nonRandomizedStringComparerHashCode3 & (long)((ulong)(-16777216))) >> 24);
				}
				if (flag2)
				{
					int nonRandomizedStringComparerHashCode4 = StringUtil.GetNonRandomizedStringComparerHashCode(appDomainAppId);
					this._DecryptionKey[4] = (byte)(nonRandomizedStringComparerHashCode4 & 255);
					this._DecryptionKey[5] = (byte)((nonRandomizedStringComparerHashCode4 & 65280) >> 8);
					this._DecryptionKey[6] = (byte)((nonRandomizedStringComparerHashCode4 & 16711680) >> 16);
					this._DecryptionKey[7] = (byte)(((long)nonRandomizedStringComparerHashCode4 & (long)((ulong)(-16777216))) >> 24);
				}
				this.DataInitialized = true;
			}
		}

		// Token: 0x0600573B RID: 22331 RVA: 0x00130B1E File Offset: 0x0012ED1E
		[Obsolete("This API exists only for backward compatibility; new framework features that require cryptographic services MUST NOT call it. New features should use the AspNetCryptoServiceProvider class instead.")]
		internal static byte[] EncryptOrDecryptData(bool fEncrypt, byte[] buf, byte[] modifier, int start, int length)
		{
			return MachineKeySection.EncryptOrDecryptData(fEncrypt, buf, modifier, start, length, false, false, IVType.Random);
		}

		// Token: 0x0600573C RID: 22332 RVA: 0x00130B2E File Offset: 0x0012ED2E
		[Obsolete("This API exists only for backward compatibility; new framework features that require cryptographic services MUST NOT call it. New features should use the AspNetCryptoServiceProvider class instead.")]
		internal static byte[] EncryptOrDecryptData(bool fEncrypt, byte[] buf, byte[] modifier, int start, int length, bool useValidationSymAlgo)
		{
			return MachineKeySection.EncryptOrDecryptData(fEncrypt, buf, modifier, start, length, useValidationSymAlgo, false, IVType.Random);
		}

		// Token: 0x0600573D RID: 22333 RVA: 0x00130B40 File Offset: 0x0012ED40
		[Obsolete("This API exists only for backward compatibility; new framework features that require cryptographic services MUST NOT call it. New features should use the AspNetCryptoServiceProvider class instead.")]
		internal static byte[] EncryptOrDecryptData(bool fEncrypt, byte[] buf, byte[] modifier, int start, int length, bool useValidationSymAlgo, bool useLegacyMode, IVType ivType)
		{
			return MachineKeySection.EncryptOrDecryptData(fEncrypt, buf, modifier, start, length, useValidationSymAlgo, useLegacyMode, ivType, !AppSettings.UseLegacyEncryption);
		}

		// Token: 0x0600573E RID: 22334 RVA: 0x00130B68 File Offset: 0x0012ED68
		[Obsolete("This API exists only for backward compatibility; new framework features that require cryptographic services MUST NOT call it. New features should use the AspNetCryptoServiceProvider class instead.")]
		internal static byte[] EncryptOrDecryptData(bool fEncrypt, byte[] buf, byte[] modifier, int start, int length, bool useValidationSymAlgo, bool useLegacyMode, IVType ivType, bool signData)
		{
			byte[] array8;
			try
			{
				MachineKeySection.EnsureConfig();
				if (!fEncrypt && signData)
				{
					if (start != 0 || length != buf.Length)
					{
						byte[] array = new byte[length];
						Buffer.BlockCopy(buf, start, array, 0, length);
						buf = array;
						start = 0;
					}
					buf = MachineKeySection.GetUnHashedData(buf);
					if (buf == null)
					{
						throw new HttpException(SR.GetString("Unable_to_validate_data"));
					}
					length = buf.Length;
				}
				if (useLegacyMode)
				{
					useLegacyMode = MachineKeySection._UsingCustomEncryption;
				}
				MemoryStream memoryStream = new MemoryStream();
				ICryptoTransform cryptoTransform = MachineKeySection.GetCryptoTransform(fEncrypt, useValidationSymAlgo, useLegacyMode);
				CryptoStream cryptoStream = new CryptoStream(memoryStream, cryptoTransform, CryptoStreamMode.Write);
				bool flag = signData || (ivType != IVType.None && MachineKeySection.CompatMode > MachineKeyCompatibilityMode.Framework20SP1);
				if (fEncrypt && flag)
				{
					int num = (useValidationSymAlgo ? MachineKeySection._IVLengthValidation : MachineKeySection._IVLengthDecryption);
					byte[] array2 = null;
					if (ivType != IVType.Random)
					{
						if (ivType == IVType.Hash)
						{
							array2 = MachineKeySection.GetIVHash(buf, num);
						}
					}
					else
					{
						array2 = new byte[num];
						MachineKeySection.RandomNumberGenerator.GetBytes(array2);
					}
					cryptoStream.Write(array2, 0, array2.Length);
				}
				cryptoStream.Write(buf, start, length);
				if (fEncrypt && modifier != null)
				{
					cryptoStream.Write(modifier, 0, modifier.Length);
				}
				cryptoStream.FlushFinalBlock();
				byte[] array3 = memoryStream.ToArray();
				cryptoStream.Close();
				MachineKeySection.ReturnCryptoTransform(fEncrypt, cryptoTransform, useValidationSymAlgo, useLegacyMode);
				byte[] array4;
				if (!fEncrypt && flag)
				{
					int num2 = (useValidationSymAlgo ? MachineKeySection._IVLengthValidation : MachineKeySection._IVLengthDecryption);
					int num3 = array3.Length - num2;
					if (num3 < 0)
					{
						throw new HttpException(SR.GetString("Unable_to_validate_data"));
					}
					array4 = new byte[num3];
					Buffer.BlockCopy(array3, num2, array4, 0, num3);
				}
				else
				{
					array4 = array3;
				}
				if (!fEncrypt && modifier != null && modifier.Length != 0)
				{
					if (!CryptoUtil.BuffersAreEqual(array4, array4.Length - modifier.Length, modifier.Length, modifier, 0, modifier.Length))
					{
						throw new HttpException(SR.GetString("Unable_to_validate_data"));
					}
					byte[] array5 = new byte[array4.Length - modifier.Length];
					Buffer.BlockCopy(array4, 0, array5, 0, array5.Length);
					array4 = array5;
				}
				if (fEncrypt && signData)
				{
					byte[] array6 = MachineKeySection.HashData(array4, null, 0, array4.Length);
					byte[] array7 = new byte[array4.Length + array6.Length];
					Buffer.BlockCopy(array4, 0, array7, 0, array4.Length);
					Buffer.BlockCopy(array6, 0, array7, array4.Length, array6.Length);
					array4 = array7;
				}
				array8 = array4;
			}
			catch
			{
				throw new HttpException(SR.GetString("Unable_to_validate_data"));
			}
			return array8;
		}

		// Token: 0x0600573F RID: 22335 RVA: 0x00130DBC File Offset: 0x0012EFBC
		private static byte[] GetIVHash(byte[] buf, int ivLength)
		{
			int num = ivLength;
			int i = 0;
			byte[] array = new byte[ivLength];
			byte[] array2 = buf;
			while (i < ivLength)
			{
				byte[] array3 = new byte[MachineKeySection._HashSize];
				int sha1Hash = UnsafeNativeMethods.GetSHA1Hash(array2, array2.Length, array3, array3.Length);
				Marshal.ThrowExceptionForHR(sha1Hash);
				array2 = array3;
				int num2 = Math.Min(MachineKeySection._HashSize, num);
				Buffer.BlockCopy(array2, 0, array, i, num2);
				i += num2;
				num -= num2;
			}
			return array;
		}

		// Token: 0x17001931 RID: 6449
		// (get) Token: 0x06005740 RID: 22336 RVA: 0x00130E26 File Offset: 0x0012F026
		private static RNGCryptoServiceProvider RandomNumberGenerator
		{
			get
			{
				if (MachineKeySection.s_randomNumberGenerator == null)
				{
					MachineKeySection.s_randomNumberGenerator = new RNGCryptoServiceProvider();
				}
				return MachineKeySection.s_randomNumberGenerator;
			}
		}

		// Token: 0x06005741 RID: 22337 RVA: 0x00130E40 File Offset: 0x0012F040
		private static void SetInnerOuterKeys(byte[] validationKey, ref byte[] inner, ref byte[] outer)
		{
			if (validationKey.Length > MachineKeySection._AutoGenValidationKeySize)
			{
				byte[] array = new byte[MachineKeySection._HashSize];
				int sha1Hash = UnsafeNativeMethods.GetSHA1Hash(validationKey, validationKey.Length, array, array.Length);
				Marshal.ThrowExceptionForHR(sha1Hash);
			}
			if (inner == null)
			{
				inner = new byte[MachineKeySection._AutoGenValidationKeySize];
			}
			if (outer == null)
			{
				outer = new byte[MachineKeySection._AutoGenValidationKeySize];
			}
			for (int i = 0; i < MachineKeySection._AutoGenValidationKeySize; i++)
			{
				inner[i] = 54;
				outer[i] = 92;
			}
			for (int i = 0; i < validationKey.Length; i++)
			{
				byte[] array2 = inner;
				int num = i;
				array2[num] ^= validationKey[i];
				byte[] array3 = outer;
				int num2 = i;
				array3[num2] ^= validationKey[i];
			}
		}

		// Token: 0x06005742 RID: 22338 RVA: 0x00130EE4 File Offset: 0x0012F0E4
		private static byte[] GetHMACSHA1Hash(byte[] buf, byte[] modifier, int start, int length)
		{
			if (start < 0 || start > buf.Length)
			{
				throw new ArgumentException(SR.GetString("InvalidArgumentValue", new object[] { "start" }));
			}
			if (length < 0 || buf == null || start + length > buf.Length)
			{
				throw new ArgumentException(SR.GetString("InvalidArgumentValue", new object[] { "length" }));
			}
			byte[] array = new byte[MachineKeySection._HashSize];
			if (UnsafeNativeMethods.GetHMACSHA1Hash(buf, start, length, modifier, (modifier == null) ? 0 : modifier.Length, MachineKeySection.s_inner, MachineKeySection.s_inner.Length, MachineKeySection.s_outer, MachineKeySection.s_outer.Length, array, array.Length) == 0)
			{
				return array;
			}
			MachineKeySection._UseHMACSHA = false;
			return null;
		}

		// Token: 0x06005743 RID: 22339 RVA: 0x00130F8C File Offset: 0x0012F18C
		[Obsolete("This API exists only for backward compatibility; new framework features that require cryptographic services MUST NOT call it. New features should use the AspNetCryptoServiceProvider class instead.")]
		internal static string HashAndBase64EncodeString(string s)
		{
			byte[] bytes = Encoding.Unicode.GetBytes(s);
			byte[] array = MachineKeySection.HashData(bytes, null, 0, bytes.Length);
			return Convert.ToBase64String(array);
		}

		// Token: 0x06005744 RID: 22340 RVA: 0x00130FBC File Offset: 0x0012F1BC
		internal static void DestroyByteArray(byte[] buf)
		{
			if (buf == null || buf.Length < 1)
			{
				return;
			}
			for (int i = 0; i < buf.Length; i++)
			{
				buf[i] = 0;
			}
		}

		// Token: 0x06005745 RID: 22341 RVA: 0x00130FE5 File Offset: 0x0012F1E5
		internal void DestroyKeys()
		{
			MachineKeySection.DestroyByteArray(this._ValidationKey);
			MachineKeySection.DestroyByteArray(this._DecryptionKey);
		}

		// Token: 0x06005746 RID: 22342 RVA: 0x00131000 File Offset: 0x0012F200
		private static void EnsureConfig()
		{
			if (!MachineKeySection.s_initComplete)
			{
				object obj = MachineKeySection.s_initLock;
				lock (obj)
				{
					if (!MachineKeySection.s_initComplete)
					{
						MachineKeySection.GetApplicationConfig();
						MachineKeySection.s_config.ConfigureEncryptionObject();
						MachineKeySection.s_initComplete = true;
					}
				}
			}
		}

		// Token: 0x06005747 RID: 22343 RVA: 0x00131060 File Offset: 0x0012F260
		internal static MachineKeySection GetApplicationConfig()
		{
			if (MachineKeySection.s_config == null)
			{
				object obj = MachineKeySection.s_initLock;
				lock (obj)
				{
					if (MachineKeySection.s_config == null)
					{
						MachineKeySection.s_config = RuntimeConfig.GetAppConfig().MachineKey;
					}
				}
			}
			return MachineKeySection.s_config;
		}

		// Token: 0x06005748 RID: 22344 RVA: 0x001310BC File Offset: 0x0012F2BC
		[Obsolete("This API exists only for backward compatibility; new framework features that require cryptographic services MUST NOT call it. New features should use the AspNetCryptoServiceProvider class instead.")]
		internal static byte[] GetEncodedData(byte[] buf, byte[] modifier, int start, ref int length)
		{
			MachineKeySection.EnsureConfig();
			byte[] array = MachineKeySection.HashData(buf, modifier, start, length);
			byte[] array2;
			if (buf.Length - start - length >= array.Length)
			{
				Buffer.BlockCopy(array, 0, buf, start + length, array.Length);
				array2 = buf;
			}
			else
			{
				array2 = new byte[length + array.Length];
				Buffer.BlockCopy(buf, start, array2, 0, length);
				Buffer.BlockCopy(array, 0, array2, length, array.Length);
				start = 0;
			}
			length += array.Length;
			if (MachineKeySection.s_config.Validation == MachineKeyValidation.TripleDES || MachineKeySection.s_config.Validation == MachineKeyValidation.AES)
			{
				array2 = MachineKeySection.EncryptOrDecryptData(true, array2, modifier, start, length, true);
				length = array2.Length;
			}
			return array2;
		}

		// Token: 0x06005749 RID: 22345 RVA: 0x00131158 File Offset: 0x0012F358
		[Obsolete("This API exists only for backward compatibility; new framework features that require cryptographic services MUST NOT call it. New features should use the AspNetCryptoServiceProvider class instead.")]
		internal static byte[] GetDecodedData(byte[] buf, byte[] modifier, int start, int length, ref int dataLength)
		{
			MachineKeySection.EnsureConfig();
			if (MachineKeySection.s_config.Validation == MachineKeyValidation.TripleDES || MachineKeySection.s_config.Validation == MachineKeyValidation.AES)
			{
				buf = MachineKeySection.EncryptOrDecryptData(false, buf, modifier, start, length, true);
				if (buf == null || buf.Length < MachineKeySection._HashSize)
				{
					throw new HttpException(SR.GetString("Unable_to_validate_data"));
				}
				length = buf.Length;
				start = 0;
			}
			if (length < MachineKeySection._HashSize || start < 0 || start >= length)
			{
				throw new HttpException(SR.GetString("Unable_to_validate_data"));
			}
			byte[] array = MachineKeySection.HashData(buf, modifier, start, length - MachineKeySection._HashSize);
			for (int i = 0; i < array.Length; i++)
			{
				if (array[i] != buf[start + length - MachineKeySection._HashSize + i])
				{
					throw new HttpException(SR.GetString("Unable_to_validate_data"));
				}
			}
			dataLength = length - MachineKeySection._HashSize;
			return buf;
		}

		// Token: 0x0600574A RID: 22346 RVA: 0x00131224 File Offset: 0x0012F424
		[Obsolete("This API exists only for backward compatibility; new framework features that require cryptographic services MUST NOT call it. New features should use the AspNetCryptoServiceProvider class instead.")]
		internal static byte[] HashData(byte[] buf, byte[] modifier, int start, int length)
		{
			MachineKeySection.EnsureConfig();
			if (MachineKeySection.s_config.Validation == MachineKeyValidation.MD5)
			{
				return MachineKeySection.HashDataUsingNonKeyedAlgorithm(null, buf, modifier, start, length, MachineKeySection.s_validationKey);
			}
			if (MachineKeySection._UseHMACSHA)
			{
				byte[] hmacsha1Hash = MachineKeySection.GetHMACSHA1Hash(buf, modifier, start, length);
				if (hmacsha1Hash != null)
				{
					return hmacsha1Hash;
				}
			}
			if (MachineKeySection._CustomValidationTypeIsKeyed)
			{
				return MachineKeySection.HashDataUsingKeyedAlgorithm(KeyedHashAlgorithm.Create(MachineKeySection._CustomValidationName), buf, modifier, start, length, MachineKeySection.s_validationKey);
			}
			return MachineKeySection.HashDataUsingNonKeyedAlgorithm(HashAlgorithm.Create(MachineKeySection._CustomValidationName), buf, modifier, start, length, MachineKeySection.s_validationKey);
		}

		// Token: 0x0600574B RID: 22347 RVA: 0x001312A0 File Offset: 0x0012F4A0
		private void ConfigureEncryptionObject()
		{
			using (new ApplicationImpersonationContext())
			{
				MachineKeySection.s_validationKey = this.ValidationKeyInternal;
				byte[] decryptionKeyInternal = this.DecryptionKeyInternal;
				if (MachineKeySection._UseHMACSHA)
				{
					MachineKeySection.SetInnerOuterKeys(MachineKeySection.s_validationKey, ref MachineKeySection.s_inner, ref MachineKeySection.s_outer);
				}
				this.DestroyKeys();
				string decryption = this.Decryption;
				if (!(decryption == "3DES"))
				{
					if (!(decryption == "DES"))
					{
						if (!(decryption == "AES"))
						{
							if (decryption == "Auto")
							{
								if (decryptionKeyInternal.Length == 8)
								{
									MachineKeySection.s_oSymAlgoDecryption = CryptoAlgorithms.CreateDES();
								}
								else
								{
									MachineKeySection.s_oSymAlgoDecryption = CryptoAlgorithms.CreateAes();
								}
							}
						}
						else
						{
							MachineKeySection.s_oSymAlgoDecryption = CryptoAlgorithms.CreateAes();
						}
					}
					else
					{
						MachineKeySection.s_oSymAlgoDecryption = CryptoAlgorithms.CreateDES();
					}
				}
				else
				{
					MachineKeySection.s_oSymAlgoDecryption = CryptoAlgorithms.CreateTripleDES();
				}
				if (MachineKeySection.s_oSymAlgoDecryption == null)
				{
					this.InitValidationAndEncyptionSizes();
				}
				MachineKeyValidation validation = this.Validation;
				if (validation != MachineKeyValidation.TripleDES)
				{
					if (validation == MachineKeyValidation.AES)
					{
						MachineKeySection.s_oSymAlgoValidation = CryptoAlgorithms.CreateAes();
					}
				}
				else if (decryptionKeyInternal.Length == 8)
				{
					MachineKeySection.s_oSymAlgoValidation = CryptoAlgorithms.CreateDES();
				}
				else
				{
					MachineKeySection.s_oSymAlgoValidation = CryptoAlgorithms.CreateTripleDES();
				}
				if (MachineKeySection.s_oSymAlgoValidation != null)
				{
					this.SetKeyOnSymAlgorithm(MachineKeySection.s_oSymAlgoValidation, decryptionKeyInternal);
					MachineKeySection._IVLengthValidation = MachineKeySection.RoundupNumBitsToNumBytes(MachineKeySection.s_oSymAlgoValidation.KeySize);
				}
				this.SetKeyOnSymAlgorithm(MachineKeySection.s_oSymAlgoDecryption, decryptionKeyInternal);
				MachineKeySection._IVLengthDecryption = MachineKeySection.RoundupNumBitsToNumBytes(MachineKeySection.s_oSymAlgoDecryption.KeySize);
				MachineKeySection.InitLegacyEncAlgorithm(decryptionKeyInternal);
				MachineKeySection.DestroyByteArray(decryptionKeyInternal);
			}
		}

		// Token: 0x0600574C RID: 22348 RVA: 0x00131424 File Offset: 0x0012F624
		private void SetKeyOnSymAlgorithm(SymmetricAlgorithm symAlgo, byte[] dKey)
		{
			try
			{
				if (dKey.Length > 8 && symAlgo is DESCryptoServiceProvider)
				{
					byte[] array = new byte[8];
					Buffer.BlockCopy(dKey, 0, array, 0, 8);
					symAlgo.Key = array;
					MachineKeySection.DestroyByteArray(array);
				}
				else
				{
					symAlgo.Key = dKey;
				}
				symAlgo.GenerateIV();
				symAlgo.IV = new byte[symAlgo.IV.Length];
			}
			catch (Exception ex)
			{
				throw new ConfigurationErrorsException(SR.GetString("Bad_machine_key", new object[] { ex.Message }), base.ElementInformation.Properties["decryptionKey"].Source, base.ElementInformation.Properties["decryptionKey"].LineNumber);
			}
		}

		// Token: 0x0600574D RID: 22349 RVA: 0x001314E8 File Offset: 0x0012F6E8
		private static ICryptoTransform GetCryptoTransform(bool fEncrypt, bool useValidationSymAlgo, bool legacyMode)
		{
			SymmetricAlgorithm symmetricAlgorithm = (legacyMode ? MachineKeySection.s_oSymAlgoLegacy : (useValidationSymAlgo ? MachineKeySection.s_oSymAlgoValidation : MachineKeySection.s_oSymAlgoDecryption));
			SymmetricAlgorithm symmetricAlgorithm2 = symmetricAlgorithm;
			ICryptoTransform cryptoTransform;
			lock (symmetricAlgorithm2)
			{
				cryptoTransform = (fEncrypt ? symmetricAlgorithm.CreateEncryptor() : symmetricAlgorithm.CreateDecryptor());
			}
			return cryptoTransform;
		}

		// Token: 0x0600574E RID: 22350 RVA: 0x0013154C File Offset: 0x0012F74C
		private static void ReturnCryptoTransform(bool fEncrypt, ICryptoTransform ct, bool useValidationSymAlgo, bool legacyMode)
		{
			ct.Dispose();
		}

		// Token: 0x0600574F RID: 22351 RVA: 0x00131554 File Offset: 0x0012F754
		[Obsolete("This API exists only for backward compatibility; new framework features that require cryptographic services MUST NOT call it. New features should use the AspNetCryptoServiceProvider class instead.")]
		internal static byte[] HexStringToByteArray(string str)
		{
			if ((str.Length & 1) == 1)
			{
				return null;
			}
			byte[] array = MachineKeySection.s_ahexval;
			if (array == null)
			{
				array = new byte[103];
				int num = array.Length;
				while (--num >= 0)
				{
					if (48 <= num && num <= 57)
					{
						array[num] = (byte)(num - 48);
					}
					else if (97 <= num && num <= 102)
					{
						array[num] = (byte)(num - 97 + 10);
					}
					else if (65 <= num && num <= 70)
					{
						array[num] = (byte)(num - 65 + 10);
					}
				}
				MachineKeySection.s_ahexval = array;
			}
			byte[] array2 = new byte[str.Length / 2];
			int num2 = 0;
			int num3 = 0;
			int num4 = array2.Length;
			while (--num4 >= 0)
			{
				int num5;
				try
				{
					num5 = (int)array[(int)str[num2++]];
				}
				catch (ArgumentNullException)
				{
					num5 = 0;
					return null;
				}
				catch (ArgumentException)
				{
					num5 = 0;
					return null;
				}
				catch (IndexOutOfRangeException)
				{
					num5 = 0;
					return null;
				}
				int num6;
				try
				{
					num6 = (int)array[(int)str[num2++]];
				}
				catch (ArgumentNullException)
				{
					num6 = 0;
					return null;
				}
				catch (ArgumentException)
				{
					num6 = 0;
					return null;
				}
				catch (IndexOutOfRangeException)
				{
					num6 = 0;
					return null;
				}
				array2[num3++] = (byte)((num5 << 4) + num6);
			}
			return array2;
		}

		// Token: 0x06005750 RID: 22352 RVA: 0x001316C0 File Offset: 0x0012F8C0
		private void InitValidationAndEncyptionSizes()
		{
			MachineKeySection._CustomValidationName = this.ValidationAlgorithm;
			MachineKeySection._CustomValidationTypeIsKeyed = true;
			string text = this.ValidationAlgorithm;
			uint num = <PrivateImplementationDetails>.ComputeStringHash(text);
			if (num <= 1416239282U)
			{
				if (num != 415037492U)
				{
					if (num != 957249328U)
					{
						if (num != 1416239282U)
						{
							goto IL_01A0;
						}
						if (!(text == "3DES"))
						{
							goto IL_01A0;
						}
					}
					else
					{
						if (!(text == "HMACSHA512"))
						{
							goto IL_01A0;
						}
						MachineKeySection._UseHMACSHA = true;
						MachineKeySection._HashSize = 64;
						MachineKeySection._AutoGenValidationKeySize = 128;
						goto IL_0425;
					}
				}
				else
				{
					if (!(text == "SHA1"))
					{
						goto IL_01A0;
					}
					MachineKeySection._UseHMACSHA = true;
					MachineKeySection._HashSize = 20;
					MachineKeySection._AutoGenValidationKeySize = 64;
					goto IL_0425;
				}
			}
			else if (num <= 2012598173U)
			{
				if (num != 1935726387U)
				{
					if (num != 2012598173U)
					{
						goto IL_01A0;
					}
					if (!(text == "HMACSHA384"))
					{
						goto IL_01A0;
					}
					MachineKeySection._UseHMACSHA = true;
					MachineKeySection._HashSize = 48;
					MachineKeySection._AutoGenValidationKeySize = 128;
					goto IL_0425;
				}
				else
				{
					if (!(text == "MD5"))
					{
						goto IL_01A0;
					}
					MachineKeySection._CustomValidationTypeIsKeyed = false;
					MachineKeySection._UseHMACSHA = false;
					MachineKeySection._HashSize = 16;
					MachineKeySection._AutoGenValidationKeySize = 64;
					goto IL_0425;
				}
			}
			else if (num != 2018892245U)
			{
				if (num != 2893537640U)
				{
					goto IL_01A0;
				}
				if (!(text == "AES"))
				{
					goto IL_01A0;
				}
			}
			else
			{
				if (!(text == "HMACSHA256"))
				{
					goto IL_01A0;
				}
				MachineKeySection._UseHMACSHA = true;
				MachineKeySection._HashSize = 32;
				MachineKeySection._AutoGenValidationKeySize = 64;
				goto IL_0425;
			}
			MachineKeySection._UseHMACSHA = true;
			MachineKeySection._HashSize = 20;
			MachineKeySection._AutoGenValidationKeySize = 64;
			goto IL_0425;
			IL_01A0:
			MachineKeySection._UseHMACSHA = false;
			if (!MachineKeySection._CustomValidationName.StartsWith("alg:", StringComparison.Ordinal))
			{
				throw new ConfigurationErrorsException(SR.GetString("Wrong_validation_enum"), base.ElementInformation.Properties["validation"].Source, base.ElementInformation.Properties["validation"].LineNumber);
			}
			MachineKeySection._CustomValidationName = MachineKeySection._CustomValidationName.Substring("alg:".Length);
			HashAlgorithm hashAlgorithm = null;
			try
			{
				MachineKeySection._CustomValidationTypeIsKeyed = false;
				hashAlgorithm = HashAlgorithm.Create(MachineKeySection._CustomValidationName);
			}
			catch (Exception ex)
			{
				throw new ConfigurationErrorsException(SR.GetString("Wrong_validation_enum"), ex, base.ElementInformation.Properties["validation"].Source, base.ElementInformation.Properties["validation"].LineNumber);
			}
			if (hashAlgorithm == null)
			{
				throw new ConfigurationErrorsException(SR.GetString("Wrong_validation_enum"), base.ElementInformation.Properties["validation"].Source, base.ElementInformation.Properties["validation"].LineNumber);
			}
			MachineKeySection._AutoGenValidationKeySize = 0;
			MachineKeySection._HashSize = 0;
			MachineKeySection._CustomValidationTypeIsKeyed = hashAlgorithm is KeyedHashAlgorithm;
			if (!MachineKeySection._CustomValidationTypeIsKeyed)
			{
				throw new ConfigurationErrorsException(SR.GetString("Wrong_validation_enum"), base.ElementInformation.Properties["validation"].Source, base.ElementInformation.Properties["validation"].LineNumber);
			}
			try
			{
				MachineKeySection._HashSize = MachineKeySection.RoundupNumBitsToNumBytes(hashAlgorithm.HashSize);
				if (MachineKeySection._CustomValidationTypeIsKeyed)
				{
					MachineKeySection._AutoGenValidationKeySize = ((KeyedHashAlgorithm)hashAlgorithm).Key.Length;
				}
				if (MachineKeySection._AutoGenValidationKeySize < 1)
				{
					MachineKeySection._AutoGenValidationKeySize = MachineKeySection.RoundupNumBitsToNumBytes(hashAlgorithm.InputBlockSize);
				}
				if (MachineKeySection._AutoGenValidationKeySize < 1)
				{
					MachineKeySection._AutoGenValidationKeySize = MachineKeySection.RoundupNumBitsToNumBytes(hashAlgorithm.OutputBlockSize);
				}
			}
			catch
			{
			}
			if (MachineKeySection._HashSize < 1 || MachineKeySection._AutoGenValidationKeySize < 1)
			{
				byte[] array = new byte[10];
				byte[] array2 = new byte[512];
				MachineKeySection.RandomNumberGenerator.GetBytes(array);
				MachineKeySection.RandomNumberGenerator.GetBytes(array2);
				byte[] array3 = hashAlgorithm.ComputeHash(array);
				MachineKeySection._HashSize = array3.Length;
				if (MachineKeySection._AutoGenValidationKeySize < 1)
				{
					if (MachineKeySection._CustomValidationTypeIsKeyed)
					{
						MachineKeySection._AutoGenValidationKeySize = ((KeyedHashAlgorithm)hashAlgorithm).Key.Length;
					}
					else
					{
						MachineKeySection._AutoGenValidationKeySize = MachineKeySection.RoundupNumBitsToNumBytes(hashAlgorithm.InputBlockSize);
					}
				}
				hashAlgorithm.Clear();
			}
			if (MachineKeySection._HashSize < 1)
			{
				MachineKeySection._HashSize = 64;
			}
			if (MachineKeySection._AutoGenValidationKeySize < 1)
			{
				MachineKeySection._AutoGenValidationKeySize = 128;
			}
			IL_0425:
			MachineKeySection._AutoGenDecryptionKeySize = 0;
			text = this.Decryption;
			if (text == "AES")
			{
				MachineKeySection._AutoGenDecryptionKeySize = 24;
				return;
			}
			if (text == "3DES")
			{
				MachineKeySection._AutoGenDecryptionKeySize = 24;
				return;
			}
			if (text == "Auto")
			{
				MachineKeySection._AutoGenDecryptionKeySize = 24;
				return;
			}
			if (!(text == "DES"))
			{
				MachineKeySection._UsingCustomEncryption = true;
				if (!this.Decryption.StartsWith("alg:", StringComparison.Ordinal))
				{
					throw new ConfigurationErrorsException(SR.GetString("Wrong_decryption_enum"), base.ElementInformation.Properties["decryption"].Source, base.ElementInformation.Properties["decryption"].LineNumber);
				}
				try
				{
					MachineKeySection.s_oSymAlgoDecryption = SymmetricAlgorithm.Create(this.Decryption.Substring("alg:".Length));
				}
				catch (Exception ex2)
				{
					throw new ConfigurationErrorsException(SR.GetString("Wrong_decryption_enum"), ex2, base.ElementInformation.Properties["decryption"].Source, base.ElementInformation.Properties["decryption"].LineNumber);
				}
				if (MachineKeySection.s_oSymAlgoDecryption == null)
				{
					throw new ConfigurationErrorsException(SR.GetString("Wrong_decryption_enum"), base.ElementInformation.Properties["decryption"].Source, base.ElementInformation.Properties["decryption"].LineNumber);
				}
				MachineKeySection._AutoGenDecryptionKeySize = MachineKeySection.RoundupNumBitsToNumBytes(MachineKeySection.s_oSymAlgoDecryption.KeySize);
				return;
			}
			else
			{
				if (this.ValidationAlgorithm == "AES" || this.ValidationAlgorithm == "3DES")
				{
					MachineKeySection._AutoGenDecryptionKeySize = 24;
					return;
				}
				MachineKeySection._AutoGenDecryptionKeySize = 8;
				return;
			}
		}

		// Token: 0x06005751 RID: 22353 RVA: 0x00131CD0 File Offset: 0x0012FED0
		internal static int RoundupNumBitsToNumBytes(int numBits)
		{
			if (numBits < 0)
			{
				return 0;
			}
			return numBits / 8 + (((numBits & 7) != 0) ? 1 : 0);
		}

		// Token: 0x06005752 RID: 22354 RVA: 0x00131CE8 File Offset: 0x0012FEE8
		private static byte[] HashDataUsingNonKeyedAlgorithm(HashAlgorithm hashAlgo, byte[] buf, byte[] modifier, int start, int length, byte[] validationKey)
		{
			int num = length + validationKey.Length + ((modifier != null) ? modifier.Length : 0);
			byte[] array = new byte[num];
			Buffer.BlockCopy(buf, start, array, 0, length);
			if (modifier != null)
			{
				Buffer.BlockCopy(modifier, 0, array, length, modifier.Length);
			}
			Buffer.BlockCopy(validationKey, 0, array, length, validationKey.Length);
			if (hashAlgo != null)
			{
				return hashAlgo.ComputeHash(array);
			}
			byte[] array2 = new byte[16];
			int sha1Hash = UnsafeNativeMethods.GetSHA1Hash(array, array.Length, array2, array2.Length);
			Marshal.ThrowExceptionForHR(sha1Hash);
			return array2;
		}

		// Token: 0x06005753 RID: 22355 RVA: 0x00131D60 File Offset: 0x0012FF60
		private static byte[] HashDataUsingKeyedAlgorithm(KeyedHashAlgorithm hashAlgo, byte[] buf, byte[] modifier, int start, int length, byte[] validationKey)
		{
			int num = length + ((modifier != null) ? modifier.Length : 0);
			byte[] array = new byte[num];
			Buffer.BlockCopy(buf, start, array, 0, length);
			if (modifier != null)
			{
				Buffer.BlockCopy(modifier, 0, array, length, modifier.Length);
			}
			hashAlgo.Key = validationKey;
			return hashAlgo.ComputeHash(array);
		}

		// Token: 0x06005754 RID: 22356 RVA: 0x00131DAC File Offset: 0x0012FFAC
		[Obsolete("This API exists only for backward compatibility; new framework features that require cryptographic services MUST NOT call it. New features should use the AspNetCryptoServiceProvider class instead.")]
		internal static byte[] GetUnHashedData(byte[] bufHashed)
		{
			if (!MachineKeySection.VerifyHashedData(bufHashed))
			{
				return null;
			}
			byte[] array = new byte[bufHashed.Length - MachineKeySection._HashSize];
			Buffer.BlockCopy(bufHashed, 0, array, 0, array.Length);
			return array;
		}

		// Token: 0x06005755 RID: 22357 RVA: 0x00131DE0 File Offset: 0x0012FFE0
		[Obsolete("This API exists only for backward compatibility; new framework features that require cryptographic services MUST NOT call it. New features should use the AspNetCryptoServiceProvider class instead.")]
		internal static bool VerifyHashedData(byte[] bufHashed)
		{
			MachineKeySection.EnsureConfig();
			if (bufHashed.Length <= MachineKeySection._HashSize)
			{
				return false;
			}
			byte[] array = MachineKeySection.HashData(bufHashed, null, 0, bufHashed.Length - MachineKeySection._HashSize);
			if (array == null || array.Length != MachineKeySection._HashSize)
			{
				return false;
			}
			int num = bufHashed.Length - MachineKeySection._HashSize;
			return CryptoUtil.BuffersAreEqual(array, 0, MachineKeySection._HashSize, bufHashed, num, MachineKeySection._HashSize);
		}

		// Token: 0x17001932 RID: 6450
		// (get) Token: 0x06005756 RID: 22358 RVA: 0x00131E3C File Offset: 0x0013003C
		internal static bool UsingCustomEncryption
		{
			get
			{
				MachineKeySection.EnsureConfig();
				return MachineKeySection._UsingCustomEncryption;
			}
		}

		// Token: 0x06005757 RID: 22359 RVA: 0x00131E48 File Offset: 0x00130048
		private static void InitLegacyEncAlgorithm(byte[] dKey)
		{
			if (!MachineKeySection._UsingCustomEncryption)
			{
				return;
			}
			MachineKeySection.s_oSymAlgoLegacy = CryptoAlgorithms.CreateAes();
			try
			{
				MachineKeySection.s_oSymAlgoLegacy.Key = dKey;
			}
			catch
			{
				if (dKey.Length <= 24)
				{
					throw;
				}
				byte[] array = new byte[24];
				Buffer.BlockCopy(dKey, 0, array, 0, array.Length);
				dKey = array;
				MachineKeySection.s_oSymAlgoLegacy.Key = dKey;
			}
		}

		// Token: 0x06005758 RID: 22360 RVA: 0x00131EB4 File Offset: 0x001300B4
		protected override void SetReadOnly()
		{
			ConfigUtil.SetFX45DefaultValue(this, MachineKeySection._propCompatibilityMode, MachineKeyCompatibilityMode.Framework45);
			base.SetReadOnly();
		}

		// Token: 0x04002E33 RID: 11827
		private const string OBSOLETE_CRYPTO_API_MESSAGE = "This API exists only for backward compatibility; new framework features that require cryptographic services MUST NOT call it. New features should use the AspNetCryptoServiceProvider class instead.";

		// Token: 0x04002E34 RID: 11828
		internal const string DefaultValidationAlgorithm = "HMACSHA256";

		// Token: 0x04002E35 RID: 11829
		internal const MachineKeyValidation DefaultValidation = MachineKeyValidation.SHA1;

		// Token: 0x04002E36 RID: 11830
		internal const string DefaultDataProtectorType = "";

		// Token: 0x04002E37 RID: 11831
		internal const string DefaultApplicationName = "";

		// Token: 0x04002E38 RID: 11832
		private static ConfigurationPropertyCollection _properties = new ConfigurationPropertyCollection();

		// Token: 0x04002E39 RID: 11833
		private static readonly ConfigurationProperty _propValidationKey = new ConfigurationProperty("validationKey", typeof(string), "AutoGenerate,IsolateApps", StdValidatorsAndConverters.WhiteSpaceTrimStringConverter, StdValidatorsAndConverters.NonEmptyStringValidator, ConfigurationPropertyOptions.None);

		// Token: 0x04002E3A RID: 11834
		private static readonly ConfigurationProperty _propDecryptionKey = new ConfigurationProperty("decryptionKey", typeof(string), "AutoGenerate,IsolateApps", StdValidatorsAndConverters.WhiteSpaceTrimStringConverter, StdValidatorsAndConverters.NonEmptyStringValidator, ConfigurationPropertyOptions.None);

		// Token: 0x04002E3B RID: 11835
		private static readonly ConfigurationProperty _propDecryption = new ConfigurationProperty("decryption", typeof(string), "Auto", StdValidatorsAndConverters.WhiteSpaceTrimStringConverter, StdValidatorsAndConverters.NonEmptyStringValidator, ConfigurationPropertyOptions.None);

		// Token: 0x04002E3C RID: 11836
		private static readonly ConfigurationProperty _propValidation = new ConfigurationProperty("validation", typeof(string), "HMACSHA256", StdValidatorsAndConverters.WhiteSpaceTrimStringConverter, StdValidatorsAndConverters.NonEmptyStringValidator, ConfigurationPropertyOptions.None);

		// Token: 0x04002E3D RID: 11837
		private static readonly ConfigurationProperty _propDataProtectorType = new ConfigurationProperty("dataProtectorType", typeof(string), "", StdValidatorsAndConverters.WhiteSpaceTrimStringConverter, null, ConfigurationPropertyOptions.None);

		// Token: 0x04002E3E RID: 11838
		private static readonly ConfigurationProperty _propApplicationName = new ConfigurationProperty("applicationName", typeof(string), "", StdValidatorsAndConverters.WhiteSpaceTrimStringConverter, null, ConfigurationPropertyOptions.None);

		// Token: 0x04002E3F RID: 11839
		private static readonly ConfigurationProperty _propCompatibilityMode = new ConfigurationProperty("compatibilityMode", typeof(MachineKeyCompatibilityMode), MachineKeyCompatibilityMode.Framework20SP1, null, null, ConfigurationPropertyOptions.None);

		// Token: 0x04002E40 RID: 11840
		private static object s_initLock = new object();

		// Token: 0x04002E41 RID: 11841
		private static bool s_initComplete = false;

		// Token: 0x04002E42 RID: 11842
		private static MachineKeySection s_config;

		// Token: 0x04002E43 RID: 11843
		private static RNGCryptoServiceProvider s_randomNumberGenerator;

		// Token: 0x04002E44 RID: 11844
		private static SymmetricAlgorithm s_oSymAlgoDecryption;

		// Token: 0x04002E45 RID: 11845
		private static SymmetricAlgorithm s_oSymAlgoValidation;

		// Token: 0x04002E46 RID: 11846
		private static byte[] s_validationKey;

		// Token: 0x04002E47 RID: 11847
		private static byte[] s_inner = null;

		// Token: 0x04002E48 RID: 11848
		private static byte[] s_outer = null;

		// Token: 0x04002E49 RID: 11849
		private bool _AutogenKey;

		// Token: 0x04002E4A RID: 11850
		private byte[] _ValidationKey;

		// Token: 0x04002E4B RID: 11851
		private byte[] _DecryptionKey;

		// Token: 0x04002E4C RID: 11852
		private bool DataInitialized;

		// Token: 0x04002E4D RID: 11853
		private static bool _CustomValidationTypeIsKeyed;

		// Token: 0x04002E4E RID: 11854
		private static string _CustomValidationName;

		// Token: 0x04002E4F RID: 11855
		private static int _IVLengthDecryption = 64;

		// Token: 0x04002E50 RID: 11856
		private static int _IVLengthValidation = 64;

		// Token: 0x04002E51 RID: 11857
		private static int _HashSize = 32;

		// Token: 0x04002E52 RID: 11858
		private static int _AutoGenValidationKeySize = 64;

		// Token: 0x04002E53 RID: 11859
		private static int _AutoGenDecryptionKeySize = 24;

		// Token: 0x04002E54 RID: 11860
		private static bool _UseHMACSHA = true;

		// Token: 0x04002E55 RID: 11861
		private static bool _UsingCustomEncryption = false;

		// Token: 0x04002E56 RID: 11862
		private static SymmetricAlgorithm s_oSymAlgoLegacy;

		// Token: 0x04002E57 RID: 11863
		private const int MD5_KEY_SIZE = 64;

		// Token: 0x04002E58 RID: 11864
		private const int MD5_HASH_SIZE = 16;

		// Token: 0x04002E59 RID: 11865
		private const int SHA1_KEY_SIZE = 64;

		// Token: 0x04002E5A RID: 11866
		private const int HMACSHA256_KEY_SIZE = 64;

		// Token: 0x04002E5B RID: 11867
		private const int HMACSHA384_KEY_SIZE = 128;

		// Token: 0x04002E5C RID: 11868
		private const int HMACSHA512_KEY_SIZE = 128;

		// Token: 0x04002E5D RID: 11869
		private const int SHA1_HASH_SIZE = 20;

		// Token: 0x04002E5E RID: 11870
		private const int HMACSHA256_HASH_SIZE = 32;

		// Token: 0x04002E5F RID: 11871
		private const int HMACSHA384_HASH_SIZE = 48;

		// Token: 0x04002E60 RID: 11872
		private const int HMACSHA512_HASH_SIZE = 64;

		// Token: 0x04002E61 RID: 11873
		private const string ALGO_PREFIX = "alg:";

		// Token: 0x04002E62 RID: 11874
		private bool _validationIsCached;

		// Token: 0x04002E63 RID: 11875
		private string _cachedValidation;

		// Token: 0x04002E64 RID: 11876
		private MachineKeyValidation _cachedValidationEnum;

		// Token: 0x04002E65 RID: 11877
		private MachineKeyCompatibilityMode _compatibilityMode = (MachineKeyCompatibilityMode)(-1);

		// Token: 0x04002E66 RID: 11878
		[Obsolete("This API exists only for backward compatibility; new framework features that require cryptographic services MUST NOT call it. New features should use the AspNetCryptoServiceProvider class instead.")]
		private static byte[] s_ahexval;
	}
}
