<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>KT200LocalHost</AssemblyName>
    <RootNamespace>HostKT200</RootNamespace>
  </PropertyGroup>
</Project>
